"""added start and end date for event

Revision ID: 911b44fa0e07
Revises: 
Create Date: 2024-11-29 14:17:02.832488

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "911b44fa0e07"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("events", sa.Column("start_date", sa.DateTime(), nullable=True))
    op.add_column("events", sa.Column("end_date", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("events", "end_date")
    op.drop_column("events", "start_date")
    # ### end Alembic commands ###
